package com.example.dbtoolbox.workbench.dialect;

import com.example.dbtoolbox.common.AppException;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;
import java.util.regex.Pattern;

/** SQL generated by the workbench. User-entered SQL is never rewritten here. */
public final class SqlDialect {
    private SqlDialect() { }

    public static String detect(Connection connection, String hint) throws SQLException {
        String value = hint == null ? "" : hint.trim().toUpperCase(Locale.ROOT);
        if (Arrays.asList("MYSQL", "POSTGRESQL", "GAUSSDB", "H2", "ORACLE", "GENERIC").contains(value)) return value;
        if ("POSTGRES".equals(value)) return "POSTGRESQL";
        String product = connection.getMetaData().getDatabaseProductName().toLowerCase(Locale.ROOT);
        if (product.contains("gauss")) return "GAUSSDB";
        if (product.contains("postgres")) return "POSTGRESQL";
        if (product.contains("mysql") || product.contains("mariadb")) return "MYSQL";
        if (product.equals("h2")) return "H2";
        if (product.contains("oracle")) return "ORACLE";
        return "GENERIC";
    }

    public static String quote(Connection connection, String identifier) throws SQLException {
        if (identifier == null || identifier.isEmpty() || identifier.indexOf('\0') >= 0) {
            throw new AppException("数据库对象名称不能为空或包含 NUL 字符");
        }
        String quote = connection.getMetaData().getIdentifierQuoteString();
        if (quote == null || quote.trim().isEmpty()) {
            // Do not interpolate unusual identifiers when a driver cannot quote them.
            if (!identifier.matches("[A-Za-z_][A-Za-z0-9_]*")) throw new AppException("此驱动未提供标识符引用方式，无法安全处理该对象名称");
            return identifier;
        }
        String closing = "[".equals(quote) ? "]" : quote;
        return quote + identifier.replace(closing, closing + closing) + closing;
    }

    public static String qualified(Connection connection, String catalog, String schema, String table) throws SQLException {
        String dialect = detect(connection, null);
        if ("MYSQL".equals(dialect)) {
            String database = present(catalog) ? catalog : schema;
            return present(database) ? quote(connection, database) + "." + quote(connection, table) : quote(connection, table);
        }
        String result = present(schema) ? quote(connection, schema) + "." + quote(connection, table) : quote(connection, table);
        if ("POSTGRESQL".equals(dialect) || "GAUSSDB".equals(dialect) || "H2".equals(dialect) || "ORACLE".equals(dialect)) return result;
        DatabaseMetaData md = connection.getMetaData();
        if (present(catalog) && md.supportsCatalogsInDataManipulation()) {
            String separator = md.getCatalogSeparator();
            if (separator == null || separator.trim().isEmpty()) throw new AppException("驱动未提供 catalog 分隔符");
            result = md.isCatalogAtStart() ? quote(connection, catalog) + separator + result : result + separator + quote(connection, catalog);
        }
        return result;
    }

    /** Escape a literal name used in JDBC metadata's pattern parameters. */
    public static String exactPattern(DatabaseMetaData md, String value) throws SQLException {
        if (value == null) return null;
        String escape = md.getSearchStringEscape();
        if (escape == null || escape.isEmpty()) return value;
        return value.replace(escape, escape + escape).replace("%", escape + "%").replace("_", escape + "_");
    }

    /** PostgreSQL JDBC reports TABLE_CAT as null and exposes only the connected database. */
    public static String metadataCatalog(Connection connection, String catalog) throws SQLException {
        String dialect = detect(connection, null);
        if ("POSTGRESQL".equals(dialect) || "GAUSSDB".equals(dialect)) {
            if (present(catalog) && connection.getCatalog() != null && !catalog.equals(connection.getCatalog())) {
                throw new AppException("此连接只能浏览当前数据库；请为其他数据库新建连接");
            }
            return null;
        }
        return catalog;
    }

    public static PreviewQuery previewSql(Connection connection, String hint, String catalog, String schema,
                                          String table, List<Map<String, Object>> filters, String orderBy,
                                          boolean descending, int offset, int limit) throws SQLException {
        return previewSql(connection, hint, catalog, schema, table, filters, "ALL", orderBy, descending, offset, limit);
    }

    public static PreviewQuery previewSql(Connection connection, String hint, String catalog, String schema, String table,
                                          List<Map<String, Object>> filters, String filterMatch, String orderBy,
                                          boolean descending, int offset, int limit) throws SQLException {
        if (!"ALL".equals(filterMatch) && !"ANY".equals(filterMatch)) throw new AppException("筛选匹配方式必须为 ALL 或 ANY");
        if (offset < 0 || limit < 1 || limit > 1000) throw new AppException("预览 offset 必须非负，limit 必须介于 1 和 1000");
        catalog = metadataCatalog(connection, catalog);
        DatabaseMetaData md = connection.getMetaData();
        Map<String, Integer> columns = new LinkedHashMap<String, Integer>();
        try (ResultSet rs = md.getColumns(catalog, exactPattern(md, schema), exactPattern(md, table), null)) {
            while (rs.next()) {
                if (same(table, rs.getString("TABLE_NAME")) && optionalSame(schema, rs.getString("TABLE_SCHEM"))
                        && optionalSame(catalog, rs.getString("TABLE_CAT"))) columns.put(rs.getString("COLUMN_NAME"), rs.getInt("DATA_TYPE"));
            }
        }
        if (columns.isEmpty()) throw new AppException("未找到表字段或没有元数据访问权限，请刷新对象树并检查 catalog/schema");
        StringBuilder sql = new StringBuilder("SELECT * FROM ").append(qualified(connection, catalog, schema, table));
        List<Object> params = new ArrayList<Object>();
        if (filters != null && filters.size() > 30) throw new AppException("单次预览最多支持 30 个筛选条件");
        boolean firstFilter = true;
        if (filters != null) for (Map<String, Object> filter : filters) {
            if (filter == null) throw new AppException("筛选条件不能为空");
            String column = string(filter.get("column"));
            if (!columns.containsKey(column)) throw new AppException("筛选字段不存在：" + column);
            Object rawOperator = filter.containsKey("operator") ? filter.get("operator") : filter.get("op");
            String operator = rawOperator == null ? "=" : rawOperator.toString().trim().toUpperCase(Locale.ROOT);
            if (!Arrays.asList("=", "!=", "<>", ">", ">=", "<", "<=", "LIKE", "NOT LIKE", "IS NULL", "IS NOT NULL").contains(operator)) {
                throw new AppException("不支持的筛选运算符：" + operator);
            }
            Object value = filter.get("value");
            if (value == null && "=".equals(operator)) operator = "IS NULL";
            if (value == null && ("!=".equals(operator) || "<>".equals(operator))) operator = "IS NOT NULL";
            if (operator.contains("LIKE") && !textType(columns.get(column))) throw new AppException("LIKE 只支持文本字段");
            sql.append(firstFilter ? " WHERE (" : "ANY".equals(filterMatch) ? " OR " : " AND ").append(quote(connection, column)).append(' ').append(operator);
            firstFilter = false;
            if (!"IS NULL".equals(operator) && !"IS NOT NULL".equals(operator)) {
                if (value == null) throw new AppException("此筛选运算符需要非空值");
                sql.append(" ?");
                params.add(typedValue(value, columns.get(column), column));
            }
        }
        if (!firstFilter) sql.append(')');
        List<String> warnings = new ArrayList<String>();
        List<String> sort = new ArrayList<String>();
        if (present(orderBy)) {
            if (!columns.containsKey(orderBy)) throw new AppException("排序字段不存在：" + orderBy);
            sort.add(quote(connection, orderBy) + (descending ? " DESC" : " ASC"));
        }
        TreeMap<Integer, String> primaryKeys = new TreeMap<Integer, String>();
        try (ResultSet rs = md.getPrimaryKeys(catalog, schema, table)) {
            while (rs.next()) if (same(table, rs.getString("TABLE_NAME")) && optionalSame(schema, rs.getString("TABLE_SCHEM"))
                    && optionalSame(catalog, rs.getString("TABLE_CAT"))) primaryKeys.put(rs.getInt("KEY_SEQ"), rs.getString("COLUMN_NAME"));
        } catch (java.sql.SQLFeatureNotSupportedException ex) {
            warnings.add("驱动不支持主键元数据，无法保证稳定翻页");
        }
        for (String key : primaryKeys.values()) if (!key.equals(orderBy)) sort.add(quote(connection, key) + " ASC");
        if (primaryKeys.isEmpty()) warnings.add("表没有可用主键；并发改动或重复排序值可能导致翻页重复/遗漏");
        if (!sort.isEmpty()) sql.append(" ORDER BY ").append(String.join(", ", sort));
        String dialect = detect(connection, hint);
        boolean paging = Arrays.asList("MYSQL", "POSTGRESQL", "GAUSSDB", "H2").contains(dialect);
        if (paging) {
            sql.append(" LIMIT ? OFFSET ?");
            params.add(limit);
            params.add(offset);
        } else {
            if (offset > 0) throw new AppException("此数据库尚未适配分页，只支持有行数上限的首屏预览");
            warnings.add("此数据库仅支持首屏预览，执行器必须使用 JDBC 行数上限");
        }
        return new PreviewQuery(sql.toString(), params, warnings, paging, limit);
    }

    public static String explainSql(Connection connection, String hint, String sql, boolean analyze) throws SQLException {
        if (sql == null || sql.trim().isEmpty()) throw new AppException("请输入要查看计划的 SQL");
        String clean = stripLeadingComments(sql).trim();
        if (clean.endsWith(";")) clean = clean.substring(0, clean.length() - 1).trim();
        String dialect = detect(connection, hint);
        if (!Arrays.asList("MYSQL", "POSTGRESQL", "GAUSSDB", "H2").contains(dialect)) {
            throw new AppException("此数据库尚未适配自动 EXPLAIN，请在 SQL 编辑器执行数据库原生计划命令");
        }
        boolean existing = Pattern.compile("(?is)^EXPLAIN\\b").matcher(clean).find();
        if (existing) {
            String options = explainOptions(clean);
            if (Pattern.compile("(?is)\\bANALY[ZS]E\\b").matcher(options).find() && !analyze) {
                throw new AppException("EXPLAIN ANALYZE 会实际执行 SQL，请启用并确认实际执行模式");
            }
            return clean;
        }
        if (!Pattern.compile("(?is)^(SELECT|WITH|INSERT|UPDATE|DELETE|MERGE|VALUES)\\b").matcher(clean).find()) {
            throw new AppException("自动 EXPLAIN 仅支持查询或 DML；其他计划语法请直接输入完整原生命令");
        }
        if ("POSTGRESQL".equals(dialect) || "GAUSSDB".equals(dialect)) return (analyze ? "EXPLAIN (ANALYZE, FORMAT JSON) " : "EXPLAIN (FORMAT JSON) ") + clean;
        return (analyze ? "EXPLAIN ANALYZE " : "EXPLAIN ") + clean;
    }

    private static String explainOptions(String sql) {
        // Mask comments and quoted tokens before locating the query. Keep offsets stable,
        // then inspect the ORIGINAL prefix as MySQL executable comments can contain ANALYZE.
        StringBuilder tokens = new StringBuilder(sql);
        int i = 0;
        while (i < sql.length()) {
            int start = i;
            char c = sql.charAt(i);
            if (c == '\'' || c == '"' || c == '`') {
                char quote = c;
                i++;
                while (i < sql.length()) {
                    if (sql.charAt(i) == '\\') { i = Math.min(sql.length(), i + 2); continue; }
                    if (sql.charAt(i++) == quote) {
                        if (i < sql.length() && sql.charAt(i) == quote) { i++; continue; }
                        break;
                    }
                }
            } else if (c == '-' && i + 1 < sql.length() && sql.charAt(i + 1) == '-') {
                while (i < sql.length() && sql.charAt(i) != '\n') i++;
            } else if (c == '/' && i + 1 < sql.length() && sql.charAt(i + 1) == '*') {
                i += 2;
                int depth = 1;
                while (i < sql.length() && depth > 0) {
                    if (i + 1 < sql.length() && sql.charAt(i) == '/' && sql.charAt(i + 1) == '*') { depth++; i += 2; }
                    else if (i + 1 < sql.length() && sql.charAt(i) == '*' && sql.charAt(i + 1) == '/') { depth--; i += 2; }
                    else i++;
                }
            } else { i++; continue; }
            for (int j = start; j < i; j++) tokens.setCharAt(j, ' ');
        }
        java.util.regex.Matcher query = Pattern.compile("(?is)\\b(SELECT|WITH|INSERT|UPDATE|DELETE|MERGE|VALUES)\\b").matcher(tokens);
        return query.find() ? sql.substring(0, query.start()) : sql;
    }

    private static String stripLeadingComments(String sql) {
        String remaining = sql.trim();
        while (remaining.startsWith("--") || remaining.startsWith("/*")) {
            int end = remaining.startsWith("--") ? remaining.indexOf('\n') : remaining.indexOf("*/");
            if (end < 0) throw new AppException("EXPLAIN SQL 只有注释或注释未闭合");
            remaining = remaining.substring(end + (remaining.startsWith("--") ? 1 : 2)).trim();
        }
        return remaining;
    }

    private static Object typedValue(Object value, int type, String column) {
        String text = String.valueOf(value);
        try {
            switch (type) {
                case Types.TINYINT: case Types.SMALLINT: case Types.INTEGER: case Types.BIGINT: return new BigDecimal(text).toBigIntegerExact();
                case Types.DECIMAL: case Types.NUMERIC: case Types.FLOAT: case Types.REAL: case Types.DOUBLE: return new BigDecimal(text);
                case Types.BOOLEAN: case Types.BIT:
                    if ("true".equalsIgnoreCase(text) || "1".equals(text)) return Boolean.TRUE;
                    if ("false".equalsIgnoreCase(text) || "0".equals(text)) return Boolean.FALSE;
                    throw new IllegalArgumentException();
                case Types.DATE: return java.sql.Date.valueOf(text);
                case Types.TIME: return java.sql.Time.valueOf(text);
                case Types.TIMESTAMP: return java.sql.Timestamp.valueOf(text.replace('T', ' '));
                default:
                    if (value instanceof Map || value instanceof List) throw new IllegalArgumentException();
                    return text;
            }
        } catch (IllegalArgumentException | ArithmeticException ex) {
            throw new AppException("筛选值与字段类型不匹配：" + column);
        }
    }

    private static boolean textType(int type) {
        return Arrays.asList(Types.CHAR, Types.VARCHAR, Types.LONGVARCHAR, Types.NCHAR, Types.NVARCHAR, Types.LONGNVARCHAR, Types.CLOB, Types.NCLOB).contains(type);
    }
    private static boolean present(String value) { return value != null && !value.isEmpty(); }
    private static boolean same(String a, String b) { return a == null ? b == null : a.equals(b); }
    private static boolean optionalSame(String a, String b) { return a == null || same(a, b); }
    private static String string(Object value) { return value == null ? null : String.valueOf(value); }

    public static final class PreviewQuery {
        public final String sql;
        public final List<Object> params;
        public final List<String> warnings;
        public final boolean pagingSupported;
        public final int limit;
        public PreviewQuery(String sql, List<Object> params, List<String> warnings, boolean pagingSupported, int limit) {
            this.sql = sql;
            this.params = Collections.unmodifiableList(new ArrayList<Object>(params));
            this.warnings = Collections.unmodifiableList(new ArrayList<String>(warnings));
            this.pagingSupported = pagingSupported;
            this.limit = limit;
        }
    }
}
