package com.example.dbtoolbox.workbench.execution;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import java.lang.reflect.*;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.file.*;
import java.sql.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

/** Opt-in real PostgreSQL check. Uses unique disposable objects and an isolated external driver. */
@EnabledIfEnvironmentVariable(named="TOOLBOX_TEST_POSTGRES_URL", matches=".+")
class PostgresCellMetadataTest {
    @Test void legacyFlagsUseRealCatalogAndFailedCatalogQueryDoesNotAbortPriorWork() throws Exception {
        URL jar=Paths.get(System.getenv("TOOLBOX_TEST_POSTGRES_DRIVER")).toUri().toURL();
        try(URLClassLoader loader=new URLClassLoader(new URL[]{jar},Driver.class.getClassLoader())) {
            Driver driver=(Driver)Class.forName("org.postgresql.Driver",true,loader).newInstance();
            Properties properties=new Properties();properties.setProperty("user",System.getenv("TOOLBOX_TEST_POSTGRES_USER"));
            properties.setProperty("password",System.getenv().getOrDefault("TOOLBOX_TEST_POSTGRES_PASSWORD",""));
            try(Connection raw=driver.connect(System.getenv("TOOLBOX_TEST_POSTGRES_URL"),properties)) {
                String table="toolbox_metadata_"+UUID.randomUUID().toString().replace("-","");
                try(Statement s=raw.createStatement()) {
                    s.execute("CREATE TABLE public."+table+"(id INT PRIMARY KEY, val VARCHAR(20), derived VARCHAR GENERATED ALWAYS AS (upper(val)) STORED, seq BIGINT GENERATED BY DEFAULT AS IDENTITY, def INT DEFAULT 7)");
                    try {
                        s.execute("INSERT INTO public."+table+"(id,val) VALUES(1,'old')");
                        boolean[] failure={false};
                        SessionService.Session session=new SessionService.Session();session.id="catalog-probe";
                        session.connection=legacy(raw,failure);
                        ExecutionRecord.Result result=preview(session,table);
                        assertTrue(result.columns.get(1).editable,result.readOnlyReason);
                        assertTrue(result.columns.get(4).editable);
                        assertFalse(result.columns.get(2).editable);assertFalse(result.columns.get(3).editable);
                        ExecutionRequest.CellChange change=new ExecutionRequest.CellChange();change.column=1;change.value="new";
                        CellEdits.Edit edit=CellEdits.prepare(session,result,change);
                        ExecutionRequest request=new ExecutionRequest();request.timeoutSeconds=5;
                        CellEdits.run(session,request,new ExecutionRecord(),new ExecutionRecord.UnitResult(),edit);
                        try(ResultSet rs=s.executeQuery("SELECT val,derived FROM public."+table)){assertTrue(rs.next());assertEquals("new",rs.getString(1));assertEquals("NEW",rs.getString(2));}
                        raw.setAutoCommit(false);s.executeUpdate("UPDATE public."+table+" SET val='pending'");
                        failure[0]=true;result=preview(session,table);
                        assertTrue(result.readOnlyReason.contains("生成列元数据兼容查询失败"));
                        assertTrue(result.readOnlyReason.contains("42P01"));
                        try(ResultSet rs=s.executeQuery("SELECT val FROM public."+table)){assertTrue(rs.next());assertEquals("pending",rs.getString(1));}
                        raw.rollback();raw.setAutoCommit(true);
                        System.out.println("Verified real PostgreSQL "+raw.getMetaData().getDatabaseProductVersion()+" / JDBC "+raw.getMetaData().getDriverVersion()+": legacy flags, catalog fallback, edit, savepoint recovery");
                    } finally {if(!raw.getAutoCommit())raw.rollback();raw.setAutoCommit(true);s.execute("DROP TABLE public."+table);}
                }
            }
        }
    }
    private static ExecutionRecord.Result preview(SessionService.Session session,String table)throws Exception {
        ExecutionRecord.Result result;
        try(Statement s=session.connection.createStatement();ResultSet rs=s.executeQuery("SELECT * FROM public."+table)) {
            result=ResultReader.read(rs,10,new ResultReader.Budget());
        }
        CellEdits.attach(session,null,"public",table,result);return result;
    }
    private static Connection legacy(Connection raw,boolean[] failure)throws Exception {
        DatabaseMetaData md=raw.getMetaData();
        DatabaseMetaData legacy=proxy(DatabaseMetaData.class,(m,a)->{
            Object value=invoke(md,m,a);
            if(m.getName().equals("getColumns"))return proxy(ResultSet.class,(rm,ra)->{
                if(rm.getName().equals("getMetaData")) {
                    ResultSetMetaData meta=((ResultSet)value).getMetaData();
                    return proxy(ResultSetMetaData.class,(mm,ma)->{
                        Object label=invoke(meta,mm,ma);
                        return (mm.getName().equals("getColumnLabel")||mm.getName().equals("getColumnName"))&&"IS_GENERATEDCOLUMN".equals(label)?"OMITTED_FLAG":label;
                    });
                }
                if(rm.getName().equals("getString")&&"IS_GENERATEDCOLUMN".equals(ra[0]))throw new SQLException("Absent flag","42703");
                return invoke(value,rm,ra);
            });
            return value;
        });
        return proxy(Connection.class,(m,a)->{
            if(m.getName().equals("getMetaData"))return legacy;
            if(failure[0]&&m.getName().equals("prepareStatement")&&((String)a[0]).startsWith("SELECT a.*, d.* FROM pg_catalog.pg_attribute"))
                return raw.prepareStatement("SELECT * FROM pg_catalog.toolbox_intentionally_missing WHERE 1=? AND 2=?");
            return invoke(raw,m,a);
        });
    }
    interface Invocation {Object run(Method method,Object[] args)throws Throwable;}
    private static Object invoke(Object object,Method method,Object[] args)throws Throwable {
        try{return method.invoke(object,args);}catch(InvocationTargetException e){throw e.getCause();}
    }
    @SuppressWarnings("unchecked") private static <T>T proxy(Class<T> type,Invocation action) {
        return (T)Proxy.newProxyInstance(type.getClassLoader(),new Class<?>[]{type},(p,m,a)->action.run(m,a));
    }
}
